core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:   /

hub_chiffred_messenger:
    resource: "@HUBChiffredMessengerBundle/Resources/config/routing.yml"
    prefix:   /message


login:
    path: /login
    defaults:
        _controller: UserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout