user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /fos

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"