hub_crypto_messenger:
    resource: "@HUBCryptoMessengerBundle/Resources/config/routing.yml"
    prefix:   /message

project:
    resource: "@ProjectBundle/Resources/config/routing.yml"
    prefix:   /project

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults:
        _controller: UserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout