sign_in:
    path:     /add
    defaults: { _controller: UserBundle:User:add }

user_mainpage:
    path: /{id}
    defaults: { _controller: UserBundle:User:mainpage}
    requirements:
            id: \d+

user_invitation:
    path:     /user_invitation
    defaults: { _controller: ProjectBundle:Invitation:listForUser}