#page principale d'un projet
project_mainpage:
    path:     /{id}
    defaults: { _controller: ProjectBundle:Default:mainPage }
    requirements:
            id: \d+

#page des membres d'un projet, permet aussi l'ajout de nouveaux membres
project_members:
    path:     /{id}/members
    defaults: { _controller: ProjectBundle:Default:members}
    requirements:
                id: \d+