project_mainpage:
    path:     /{id}
    defaults: { _controller: ProjectBundle:Default:mainPage }
    requirements:
            id: \d+
project_invitation:
    path:     /{id}/project_invitation
    defaults: { _controller: ProjectBundle:Invitation:listForProject}
    requirements:
                id: \d+