#page principale d'un projet
project_mainpage:
    path:     /{id}
    defaults: { _controller: ProjectBundle:Project:mainPage }
    requirements:
            id: \d+

#page des membres d'un projet, permet aussi l'ajout de nouveaux membres
project_members:
    path:     /{id}/members
    defaults: { _controller: ProjectBundle:Project:members}
    requirements:
                id: \d+

add_user_invitation:
    path:     /{id}/adduser
    defaults: { _controller: ProjectBundle:Invitation:addInvitation}
    requirements:
                id: \d+

delete_invitation:
    path:     /delete-invitation/{invitation_id}
    defaults: { _controller: ProjectBundle:Invitation:deleteInvitation}
    requirements:
                invitation_id: \d+

accept_invitation:
    path:     /accept-invitation/{invitation_id}
    defaults: { _controller: ProjectBundle:Invitation:acceptInvitation}
    requirements:
                invitation_id: \d+


decline_invitation:
    path:     /decline-invitation/{invitation_id}
    defaults: { _controller: ProjectBundle:Invitation:declineInvitation}
    requirements:
                invitation_id: \d+

new_project:
    path:   /project/new
    defaults: { _controller: ProjectBundle:Project:newProject}