#page principale d'un projet
project_mainpage:
    path:     /{id}
    defaults: { _controller: ProjectBundle:Project:mainPage }
    requirements:
            id: \d+

#page des membres d'un projet, permet aussi l'ajout de nouveaux membres
project_members:
    path:     /{id}/members
    defaults: { _controller: ProjectBundle:Project:members}
    requirements:
                id: \d+

add_user_invitation:
    path:     /{id}/adduser
    defaults: { _controller: ProjectBundle:Invitation:addInvitation}
    requirements:
                id: \d+

delete_invitation:
    path:     /{project_id}/delete-invitation/{user_id}
    defaults: { _controller: ProjectBundle:Invitation:deleteInvitation}
    requirements:
                project_id: \d+
                user_id: \d+